version: 0.2

# env:
#   parameter-store:
#     DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
#     DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
#     DOCKER_REGISTRY_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Building Docker image..."
      # - docker login
      # - echo docker login
      # - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      # - echo test_new
      # - echo "$DOCKER_REGISTRY_URL"
      # - echo "$DOCKER_REGISTRY_USERNAME"
      # - docker build -t "https://hub.docker.com/biloocabba/simple-python-flask-app:latest" .
      # - docker push "https://hub.docker.com/biloocabba/simple-python-flask-app:latest"
      - docker build -t simple-python-flask-app .
      - docker tag simple-python-flask-app:latest 850706444982.dkr.ecr.eu-central-1.amazonaws.com/simple-python-flask-app:latest
      - docker push 850706444982.dkr.ecr.eu-central-1.amazonaws.com/simple-python-flask-app:latest
  post_build:
    commands:
      - echo "Build completed successfully!"
# artifacts:
#   files:
#     - '**/*'
#   base-directory: ../simple-python-app